version: 2
updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
      assignees:
          - "ponurakk"
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
      assignees:
          - "ponurakk"
